#!/bin/bash

[ $# -ge 1 ] || { echo "Usage: $0 /path/to/tarball"; exit 1; }
BUNDLE_DIR=$1
mkdir -p $BUNDLE_DIR

FIRE_SCRIPT=${0//bundle/fire}
FUZZTAINER_PATH=$()
FUZZTAINER_LIBS=$($FUZZTAINER_PATH/libs/ )
FUZZTAINER_LD=$()
cp -L $FUZZTAINER_PATH $FUZZTAINER_LIBS $FUZZTAINER_LD $BUNDLE_DIR
cp -L $FIRE_SCRIPT $BUNDLE_DIR/fire
